utils::globalVariables(c("gtf", "bed", "name", "path_to_out", "start", "end", "strand", "seqnames", "score", "input", ":="))


# validate filter variables before evaluation 
# (data.table already handles the errors quite nice BUT truncates the available columns which is not very helpful after all,
# furthermore partially matching names eg with a typo would sometimes be used, sometimes not -> own helper = more control
check_filtering_variables <- function(expression, annotation, caller_env) {
  vars <- all.vars(expression)
  unknown <- vars[!(vars %in% names(annotation))]
  unknown <- unknown[!vapply(unknown, exists, logical(1), envir = caller_env)]
  if(length(unknown) > 0) stop("Unknown filter variable(s): ", paste(unknown, collapse = ", "), 
                               "\nAvailable columns for filtering: ", paste(names(annotation), collapse = ", "), 
                               call. = FALSE) # only print message, not the call 
}

# feature names as written to the the bed, generated based on feature type
gtf_feature_names <- function(annotation) {
  annotation[, name := NA_character_]
  annotation[type == "gene" | type == "aggregate_gene", name := gene_id]
  annotation[type == "transcript", name := paste(gene_id, transcript_id, sep = "-")]
  annotation[type == "exonic_part", name := paste(gene_id, exonic_part_number, sep = "-")]
  annotation[type == "exon",       name := paste(gene_id, transcript_id, exon_number, sep = "-")]
  annotation
}

#' Create genomic regions with upstream-downstream sizes and optional filters.
#'
#' @rdname make_windows
#'
#' @param input_file GTF/GFF or BED file
#' @param upstream Upstream size
#' @param downstream Downstream size
#' @param path_to_output File path to write output. Creates dirs if they do not exist
#' @param position A character string ('start' or 'end') to specify
#' if the new region should be extended around only one coordinate.
#' Default is `NULL`.
#' @param save_pars_to A character string for the file to save the parameters.
#' Default is a "config.json" file in the same directory as the output.
#' @param filter Filtering expressions generated by filter_gtf_by().
#'   Used to subset GTF entries before window generation.
#'   Defaults to `filter_gtf_by()` (no filtering).
#'
#' @returns Invisibly a data frame in BED format with specified window and filter criteria.
#' Columns are "seqnames", "start", "end", "name", "score", "strand".
#' 'seqnames' and 'strand' are factors.
#' As a side effect, it writes the data frame to `path_to_output` as a TSV file
#' if specified.
#'
#' @details
#' make_windows extends the annotations in the input file by the given upstream
#' and downstream regions, depending on the strand: A gene's start on the
#' minus strand is its end coordinate.
#' It is also possible to focus on a single coordinate by specifying `position`.
#' A region is built around the given coordinate, from `upstream`
#' bases back to `downstream` bases forward if it is on the plus strand,
#' and vice versa for the minus strand.
#'
#' If GTF is provided, the `name` column is populated based on feature type:
#' * **gene/aggregate_gene**: Uses `gene_id`.
#' * **transcript**: Combines `gene_id` and `transcript_id`.
#' * **exonic_part**: Combines `gene_id` and `exonic_part_number`.
#' * **exon**: Combines `gene_id`, `transcript_id`, and `exon_number`.
#'
#' If using `filter`, an error is thrown if used with a BED file or an incompatible format.
#'
#'
#'
#' @export
#'
#' @examples
#' example_file <- system.file("extdata", "data", "example.gtf", package = "metageneR")
#' result <- make_windows(input_file=example_file,
#'                        upstream = 1000, downstream = 2000,
#'                        position = "start",
#'                        filter = filter_gtf_by())
#' print(head(result))
make_windows <- function(input_file, upstream = 0, downstream = 0,
                         path_to_output = NULL, position = NULL,
                         save_pars_to = NULL, filter = filter_gtf_by()) {
  params <- as.list(environment())
  score <- NA

  ##### Argument checks #####
  if (missing(input_file)) {
    stop("Missing required arguments: input_file")
  }

  is_gtf <- FALSE # use for ID column creation
  if(endsWith(input_file, ".gtf") | endsWith(input_file, ".gff")) {
    is_gtf <- TRUE
    imported_file <- rtracklayer::import(input_file) %>% # seqnames, start, end, width, strand, source, type, score, phase, gene_id ...
      as.data.frame()
  } else if (endsWith(input_file, ".bed")) {
    imported_file <- rtracklayer::import(input_file) %>% # seqnames, start, end, width, strand, name, score
      as.data.frame()
    if(length(filter) > 0) {
      stop("GTF filters cannot be used with input file of format BED.")
    }
  } else {
    stop(paste0("Provided input file (", input_file, ") is of wrong format. Should: .gtf, .gff or .bed"))
  }

  # Ensure `filter` is a list (returned by filter_gtf_by)
  if (!is.null(filter) && !is.call(filter)) {
    stop("'filter' must be a call object. Use filter_gtf_by().")
  }

  # Check if elements in filter are actually language objects
  if (length(filter) > 0 && !all(sapply(filter, is.language))) {
    stop("All elements in 'filter' must be unquoted language expressions.")
  }

  # optional argument check
  if(!is.null(position) && !(position %in% c("start", "end"))) {
    stop("Position argument should be either 'start' or 'end' !")
  }

  # Create the directory path in out if they don't exist
  dir_path <- NULL
  if (!is.null(path_to_output)) {
    dir_path <- dirname(path_to_output)
    if (dir_path != "." && !dir.exists(dir_path)) {
      dir.create(dir_path, recursive = TRUE)
    }
  }

  # ================ Config and Logs  ================
  if (is.null(save_pars_to) && !is.null(path_to_output)) {
    save_pars_to <- file.path(dirname(path_to_output),
                              paste0(tools::file_path_sans_ext(basename(input_file)), ".json"))
  } # if the user has not specified a config file but is writing to a file
  # just a utility, since writing an output generally means the file config
  # might be needed later on or in another script

  ### logger setting
  # no path_to_output means no natural directory for a log file: fall back to console-only logging
  log_file <- NULL
  if (!is.null(dir_path)) {
    log_file <- file.path(dir_path, paste0("log_make_windows_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".txt"))
  }

  if(!is.null(save_pars_to)) {
    if (!is.null(filter)) { # convert 'call' type to string
      params$filter <- lapply(filter, function(x) paste(deparse(x), collapse = " "))
    }
    params$log_file <- log_file
    write_config("make_windows", path = save_pars_to, params)
  }

  logger <- create_logger("make_windows", params, log_file = log_file)
  on.exit(logger(close = TRUE), add = T)
  if (!is.null(log_file)) message("[make_windows] Log file: ", log_file)

  #  ========================== Creating BED ==========================
  annotation <- data.table::setDT(imported_file)

  # filter by gtf arguments (feature and 9th column of gtf)
  # combine each filter with ANDs
  if (length(filter) > 0) {
    combined_expr <- Reduce(function(x, y) bquote(.(x) & .(y)), filter)
    caller_env <- parent.frame()
    # check for correct filtering attributes first
    check_filtering_variables(combined_expr, annotation, caller_env)
    keep_features <- eval(combined_expr, envir = annotation, enclos = caller_env)
    annotation <- annotation[keep_features]
    if (nrow(annotation) == 0) {
      stop("Filtering resulted in 0 rows. Check your filter arguments.")
    }
  }

  if (!data.table::is.data.table(annotation)) stop("IS NOT DT")
  # Adjust start and end based on position
  if (!is.null(position) && position == "start") {
    # TSS: plus strand → start coord; minus strand → end coord
    annotation[strand == "+", end := start]
    annotation[strand == "-", start := end]
  } else if (!is.null(position) && position == "end") {
    # TES: plus strand → end coord; minus strand → start coord
    annotation[strand == "+", start := end]
    annotation[strand == "-", end := start]
  }

  # Apply upstream/downstream logic
  annotation[, `:=`(
    start = fifelse(strand == "+", start - 1 - upstream, start - 1 - downstream),
    end   = fifelse(strand == "+", end + downstream, end + upstream)
  )]

  # if score not found, fill with dot in .bed annotation
  annotation[, score := as.character(score)]
  annotation[is.na(score), score := "."]

  # Remove regions where coordinates go over the edge with a message
  negative_detected <- annotation[, start < 0 | end < 0]
  if (any(negative_detected, na.rm = TRUE)) {
    message(paste("Negative coordinates filtered out!", sum(negative_detected, na.rm = TRUE), "rows eliminated"))
  }

  annotation <- annotation[!negative_detected]

  # Create name column based on identifiers if GTF is given
  if (is_gtf) {
    annotation <- gtf_feature_names(annotation)
  }
  annotation <- annotation[, .(seqnames, start, end, name, score, strand)]

  # row number for tracking changes and logging
  message(paste0("Input had ", nrow(imported_file),
                " rows, output has ", nrow(annotation), " rows (",
                data.table::uniqueN(annotation), " unique)."))

  if(!is.null(path_to_output)) {
    annotation %>%
      data.table::fwrite(file.path(path_to_output), col.names = FALSE, sep = "\t")
    message(paste("File has been written:", path_to_output))
    invisible(annotation)
  } else {
    return(annotation)
  }
}

#' @rdname make_windows
#'
#' @param ... Unquoted logical expressions to filter the GTF data. Use commas
#' to separate multiple conditions (which are joined with an "AND" logic).
#'
#' @details
#' To filter entries from a GTF/GFF file, use logical operators
#' (`==`, `%in%`, `>`, etc.) using the column names of the annotation object.
#' Comma-separated expressions are reduced by concatenating them with "AND".
#' The function uses non-standard evaluation and applies the filters in a data.table environment.
#' This data.table is the object created by `rtracklayer::import()` from the provided annotation file,
#' which should contain columns like `seqnames`, `start`, `end`, `strand`, `source`, `type`, `gene_id`, `transcript_id`, etc.
#' Here are some examples of GTF variables one can use to filter:
#' seqnames, start, end, width, strand, source, type, score, phase, gene_id,
#' gene_version, gene_name, gene_source, gene_biotype, transcript_id, transcript_version,
#' transcript_name, transcript_source, transcript_biotype, tag, transcript_support_level,
#' exon_number, exon_id, exon_version, protein_id, protein_version, ccds_id...
#'
#' **Logical Operations:**
#' * **AND:** Separate expressions with commas (or use `&`): `type == "exon", gene_name == "GAPDH"`.
#' * **OR:** Use the `|` operator within a single expression: `gene_name == "GAPDH" | gene_name == "ACTB"`.
#' * **Multiple Values:** To match ANY value in a set, use `%in%`: `type %in% c("gene", "exon")`.
#'
#' @note
#' Do not use `&&` or `||` as these are not vectorized and will only
#' evaluate the first row of the data.
#'
#' @returns A list of language objects (calls) representing the filter expressions.
#' NULL if called empty (`filter_gtf_by()`).
#' @export
#'
#' @examples
#' filter_gtf_by(type == "gene")
#' filter_gtf_by(type == "exon", source == "HAVANA")
#' filter_gtf_by(gene_name %in% c("GAPDH", "ACTB") | type == "transcript")
filter_gtf_by <- function(...) substitute(list(...))[-1]


#' extract ids from a GTF/GFF using filter expressions
#' 
#' applies the same filter syntax as \code{\link{filter_gtf_by}()} and returns character vector of matching ids, 
#' ready to use for \code{ids_to_subset} in \code{\link{plot_metagene_experiment}}
#' 
#' @param input_file path to a GTF or GFF
#' @param filter Filtering expressions generated by filter_gtf_by().
#'   Used to subset GTF entries before window generation.
#'   Defaults to \code{\link{filter_gtf_by}} (no filtering).
#' @param id_column Default \code{NULL}, returns ids in the same format as \code{\link{make_windows}} generates. This output can be used for \code{ids_to_subset}. 
#'  Set a gtf column name (e.g. \code{"gene_name"}) to get values of that column instead.
#' @returns A character vector of unique ids matching the filtering criteria. 
#' @export
#' @examples
#' gtf <- system.file("extdata", "data", "example.gtf", package = "metageneR")
#' ids <- ids_from_gtf(gtf, filter = filter_gtf_by(type == "gene"))
#' # plot_metagene_experiment(..., ids_to_subset = ids)

ids_from_gtf <- function(input_file, filter = filter_gtf_by(), id_column = NULL) {
  ##### Argument checks #####
  # basically same as for make_windows
  if (missing(input_file)) {
    stop("Missing required arguments: input_file")
  }
  
  if(!grepl("\\.(gtf|gff)$", input_file, ignore.case = TRUE)) {
    stop("ids_from_gtf() requires a GTF or GFF")
  }
  
  # Ensure `filter` is a list (returned by filter_gtf_by)
  if (!is.null(filter) && !is.call(filter)) {
    stop("'filter' must be a call object. Use filter_gtf_by().")
  }
  
  ### run
  # again as for make_windows
  annotation <- data.table::setDT(as.data.frame(rtracklayer::import(input_file)))
  
  if(length(filter) > 0) {
    combined_expr <- Reduce(function(x, y) bquote(.(x) & .(y)), filter)
    caller_env <- parent.frame()
    # check for correct filtering attributes first
    check_filtering_variables(combined_expr, annotation, caller_env)
    keep_features <- eval(combined_expr, envir = annotation, enclos = caller_env)
    annotation <- annotation[keep_features]
    if (nrow(annotation) == 0) {
      stop("Filtering resulted in 0 rows. Check your filter arguments.")
    }
  }
  
  if(is.null(id_column)) {
    ids <- gtf_feature_names(annotation)$name
    ids <- unique(ids[!is.na(ids)])
    if(length(ids) == 0) stop("No feature names could be built. Filter for one of [gene, aggregate_gene, transcript, exonic_part and exon] or set id_column")
    return(ids)
  }
 
  # make sure column is present
  if(!(id_column %in% names(annotation))) {
    stop(paste("column", id_column, "not found. columns avalaible:", paste(names(annotation), collapse = ",")))
  }
  # filter
  unique(as.character(annotation[[id_column]]))
  
}


