# Manage namespaces and utility functions

#' @importFrom magrittr %>%
#' @importFrom data.table := fifelse fread %chin% .SD
NULL



### INTERNALS ###

# saves the functions parameter to the json file given
# it adds new parameter set if the config exists
write_config <- function(caller_name, path, params) {
  config <- list()
  if (file.exists(path)) {
    config <- jsonlite::read_json(path)
  }

  # save the new caller
  config[[caller_name]] <- params
  jsonlite::write_json(config, path = path,
                       pretty = TRUE, auto_unbox = TRUE)
}

# caller_name: function name
# args: named list of parameter and values
# the returned logger STOPS the process if an error is thrown (type = "error")
create_logger <- function(caller_name, args, log_file = NULL) {
  log_con <- NULL
  if (!is.null(log_file)) {
    log_con <- file(log_file, open = "at")
    timestamp <- format(Sys.time(), "%Y-%m-%d %H:%M:%S") # header
    # Clean args for printing
    valid_args <- args[!vapply(args, is.null, logical(1))]
    args_str <- paste(names(valid_args), "=", vapply(valid_args, toString, character(1)), collapse = ", ")

    cat(paste0("--- LOG START: ", caller_name, " ---\n"), file = log_con)
    cat(paste0("Time: ", timestamp, "\n"), file = log_con)
    cat(paste0("Args: ", args_str, "\n\n"), file = log_con)
  }

  # 2. Define the Logging Function
  # wrapper for message(), warning(), and stop()
  # message becomes default
  logger_func <- function(..., type = c("message", "warning", "error"), close = FALSE) {
      if (close) {
      if (!is.null(log_con) && isOpen(log_con)) {
        cat(paste0("--- LOG END ---\n"), file = log_con)
        close(log_con)
      }
      return(invisible(NULL))
    }

    type <- match.arg(type) # Enforce valid types
    msg_content <- paste(...)
    timestamp   <- format(Sys.time(), "%H:%M:%S")

    # prefixes for the log file
    prefix <- switch(type,
                     "message" = "[INFO] ",
                     "warning" = "[WARN] ",
                     "error"   = "[ERR]  "
    )

    full_log_line <- paste0("[", timestamp, "] ", prefix, msg_content)

    # --- Write to logfile ---
    if (!is.null(log_con) && isOpen(log_con)) {
      cat(full_log_line, "\n", file = log_con)
      # Force flush to ensure it's written immediately in case of crash later
      flush(log_con)
    }

    # --- Show on Console ---
    if (type == "message") {
      message(msg_content)
    } else if (type == "warning") {
      warning(msg_content, call. = FALSE, immediate. = TRUE)
    } else if (type == "error") {
      stop("Logger stopped the whole process:\n", msg_content, call. = FALSE)
    }
  }

  return(logger_func)
}


#' Utility function: naming output with parameters
#'
#' Creates a standard name based on given parameters.
#' Originally created for use with make_windows, hence parameters like
#' input_file, upstream and downstream will be ignored.
#'
#' @param enclosing_dir A character string indicating the directory of the file.
#' @param pars A named list of character string arguments. The names correspond to the parameters,
#' the values to the arguments.
#' @param ext A character string of extension.
#'
#' @returns A character vector of file path generated by the parameters.
#' @export
#'
#' @examples
#' pars$make_windows$path_to_output <- name_output_with(out_dir, pars$make_windows, ".bed")
name_output_with <- function(enclosing_dir, pars, ext) {
  stopifnot(c("input_file", "upstream", "downstream") %in% names(pars))

  filebase <- sub("\\.[^.]*$", "", basename(pars$input_file))

  # upstream & downstream first
  updown <- c(
    sprintf("%sup", pars$upstream),
    sprintf("%sdown", pars$downstream)
  )

  extra_keys <- setdiff(names(pars), c("input_file", "upstream", "downstream", "path_to_output"))
  extra_parts <- as.character(pars[extra_keys])
  extra_parts <- extra_parts[extra_parts != ""]  # remove empty args

  # Combine all parts
  filename <- paste(c(filebase, updown, extra_parts), collapse = "_")

  # Add .bed extension
  filename <- paste0(filename, ext)
  file.path(enclosing_dir, filename)
}


